steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build model container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-images/api:latest',
    '-f',
    'dockerfiles/api.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push model container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/docker-images/api:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY