_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
batch_size:
    value: 64
epochs:
    value: 10
k_discriminator:
    value: 3
latent_space_size:
    value: 1000
learning_rate:
    value: 2e-05
random_state:
    value: 42
