program: src/group83_mlops/train.py
name: Sweep
project: group83-MLOps-02476
method: random
parameters:
  learning-rate:
    min: 0.000005
    max: 0.0005
  batch-size:
    values: [16, 32, 64]
  epochs:
    min: 20
    max: 50
    q: 2
  k-discriminator:
    values: [2, 3, 4]
  run_cap: 20