program: src/group83_mlops/train.py
name: Sweep
method: bayes
metric:
  goal: minimize
  name: loss
parameters:
  learning-rate:
    min: 0.000005
    max: 0.0005
  batch-size:
    values: [16, 32, 64]
  epochs:
    values: [15, 25, 35]
  k-discriminator:
    values: [2, 3, 4]