name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/*.yaml"
      - "**/*.dvc"
      - "**/*.json"
      - "**/*.sh"
      - "**/*.ps1"
      - "**/*.toml"

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 20
    strategy:
      matrix:
        operating-system: ["windows-latest", "ubuntu-latest"]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
          pip install -e .
          pip list
      
      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_JSON_SERVACC }}
      
      - name: Get DVC Data
        run: |
          dvc pull --no-run-cache
      
      - name: Run tests & coverage
        run: |
          coverage run -m pytest tests/
          coverage report -i -m --data-file=.coverage
